const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('folio', {
  reloadPdf: (source, version) => ipcRenderer.invoke('pdf:reload', source, version),
  macOS: process.platform === 'darwin',
  setDefaultPdfApp: () => ipcRenderer.invoke('pdf:default'),
  repairPdfOpening: () => ipcRenderer.invoke('pdf:repair'),
  recents: () => ipcRenderer.invoke('library:recents'),
  openRecent: id => ipcRenderer.invoke('library:open', id),
  removeRecent: id => ipcRenderer.invoke('library:remove', id),
  removeVoice: id => ipcRenderer.invoke('voice:remove', id),
  nextPdf: () => ipcRenderer.invoke('pdf:next'),
  onPendingPdf: callback => { const listener = () => callback(); ipcRenderer.on('pdf:pending', listener); return () => ipcRenderer.removeListener('pdf:pending', listener); },
  voices: () => ipcRenderer.invoke('voice:list'),
  inspectVoice: id => ipcRenderer.invoke('voice:inspect', id),
  saveVoice: profile => ipcRenderer.invoke('voice:save', profile),
  openPdf: () => ipcRenderer.invoke('pdf:open'),
  savePdf: (name, data) => ipcRenderer.invoke('pdf:save', name, data),
  ttsStatus: () => ipcRenderer.invoke('tts:status'),
  chooseVoice: () => ipcRenderer.invoke('voice:choose'),
  speak: (text, voice, language, reference) => ipcRenderer.invoke('tts:speak', { text, voice, language, reference }),
  stopSpeech: () => ipcRenderer.invoke('tts:stop'),
  setDirty: dirty => ipcRenderer.send('document:dirty', Boolean(dirty)),
});
